### ISSUE TITLE
Automate account approvals

### ISSUE THREAD

**Issue by tylerbhughes** [urbanengine/OpenHuntsville#134]
With version 2.0 being live and with CoWorking Night about to start using openHSV we will soon be seeing an influx of account creations. It would be nice if we could remove some of the account approval burdens from site admins. Below are a few things I think we could do to make this easier.

1. I'm not sure what all criteria we currently look for before we approve this user but whatever those are we should make those fields required so the user has to enter them in before they can finish creating their account. This should also apply to editing an account that way those who are currently not approved will get automatically approved once they meet the requirements.
2. Validate user location. I'm not sure how we want to do this, whether we have the user enter their zip code and then we do a lookup to see if it's within a given mile range or if we want to validate the user's location some other way. I'm open to suggestions on this.
3. Add a way to send users an email letting them know that their profile isn't complete. We could probably work up a way to make this run on a weekly basis.

**Comment by skylenewman** [comment]
How many users do you see a site admin needing to approve?

From a "business" perspective, does it make more sense to automate the
process or keep human interaction?

What would this displace in the development pipeline?

On Feb 27, 2017 8:49 AM, "Tyler Hughes" <notifications@github.com> wrote:

With version 2.0 being live and with CoWorking Night about to start using
openHSV we will soon be seeing an influx of account creations. It would be
nice if we could remove some of the account approval burdens from site
admins. Below are a few things I think we could do to make this easier.

   1. I'm not sure what all criteria we currently look for before we
   approve this user but whatever those are we should make those fields
   required so the user has to enter them in before they can finish creating
   their account. This should also apply to editing an account that way those
   who are currently not approved will get automatically approved once they
   meet the requirements.
   2. Validate user location. I'm not sure how we want to do this, whether
   we have the user enter their zip code and then we do a lookup to see if
   it's within a given mile range or if we want to validate the user's
   location some other way. I'm open to suggestions on this.
   3. Add a way to send users an email letting them know that their profile
   isn't complete. We could probably work up a way to make this run on a
   weekly basis.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHuntsville/hntsvll/issues/134>, or mute the thread

**Comment by skylenewman** [comment]
Also, using Heroku Scheduler with a rake task would be the way to automate
this.

**Comment by davidhjones** [comment]
Honestly I don't know that this is an issue. Maybe to mitigate the "limbo" issue we can automate an email that is sent to the admins when a user signs up. That way we'll know to go approve it. The problem with automatic approval is that how can we really tell that someone isn't just spamming us with account creations, but falling within the acceptable guidelines? We can talk this through. but it may be more work that what its worth. Realistically it doesn't take much time to go in and approve accounts, especially when the person's account is someone you recognize

**Comment by skylenewman** [comment]
I see both arguments.

What about the kiosk mode you talked about? What about group admins
inviting with unique tokens like PW reset? What about approval by email?

I like the idea of a con job series that nudges individuals to complete or
delete.


On Feb 27, 2017 10:26 AM, "davidhjones" <notifications@github.com> wrote:

Honestly I don't know that this is an issue. Maybe to mitigate the "limbo"
issue we can automate an email that is sent to the admins when a user signs
up. That way we'll know to go approve it. The problem with automatic
approval is that how can we really tell that someone isn't just spamming us
with account creations, but falling within the acceptable guidelines? We
can talk this through. but it may be more work that what its worth.
Realistically it doesn't take much time to go in and approve accounts,
especially when the person's account is someone you recognize

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OpenHuntsville/hntsvll/issues/134#issuecomment-282770325>,
or mute the thread

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
