### ISSUE TITLE
Expose CWN BHM flyer API Endpoint

### ISSUE THREAD

**Issue by davidhjones** [urbanengine/OpenHuntsville#152]
Expose CWN BHM flyer API Endpoint

**Comment by tylerbhughes** [comment]
I'm working on exposing the API endpoints for Birmingham now but ran into a small snag. Creating an endpoint for all events was easy. I'm able to get all the upcoming events for the group and it doesn't conflict with the events for our CoWorking Night group. The issue is that with the flyer we bsaed everything on a CoWorking Night instance number. If everything for Birmingham is under one group how would we separate the events from one CoWorking Night to the next when we query the database?

**Comment by tylerbhughes** [comment]
This was done previously but never closed.
