### ISSUE TITLE
Investigate character limit issue

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#41]
Michael Carroll ran into an issue that when the character count on bio reached 0, not -1, he was unable to save and there was no warning.

We should just cut off the text.

**Comment by chrisbeaman** [comment]
Sounds good to me.

**Comment by tylerbhughes** [comment]
Now that openHuntsville handles groups and events we need to do this to other pages as well. Below are the pages that will need to be updated. While we're at it we should probably make sure that all of these fields also show the user how many characters they have left. That way they know why they can't enter any more.

Below are the fields that will need to be updated. I've added them as checkboxes so that I can mark them off once complete.

**Edit Page**
- [ ] Bio

**Schedule/Edit an Event**
- [ ] Name
- [ ] Summary
- [ ] Description

**Create/Edit a Group**
- [ ] Name
- [ ] Description

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this bug has been removed from our roadmap.
