### ISSUE TITLE
Stop reload on mobile category selection

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#43]

**Comment by chrisbeaman** [comment]
@skylenewman why?

**Comment by skylenewman** [comment]
Reload takes more bandwidth/time, which is compounded on mobile device. This should have read **sub**-category selection. It works properly on desktop.

**Comment by RandomlyKnighted** [comment]
@skylenewman My only concern with doing this is when you go back to the main category from the sub-category then you'll get another page load which doesn't really solve the original problem. 

We've talked about refactoring the UI at some point when that happens perhaps we can change the category section on the left so that it works more like a filter than a navigation. If we do that then we would need to get all the users at once then filter or unfilter based on the user selection. It'd require a little more work than what you originally mentioned but I think it would solve the actual problem at hand. What do you think?

CC: @chrisbeaman @davidhjones what are you thoughts?

**Comment by skylenewman** [comment]
The approach you outline for all was what I was anticipating on doing at
the category level. Page load time is noticeable when you're retrieving
hundreds of listings and images.

I think that this could be put off in favor of other performance
improvements like `fastlink`

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this bug has been removed from our roadmap.
